// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwiwayxzfuydgrxwjmip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3aXdheXh6ZnV5ZGdyeHdqbWlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjQ1NzYsImV4cCI6MjA2ODg0MDU3Nn0.dJ27z2B_Kcfz77FsKhO7T0_uWTpUyEfHSYXsC6j64cE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});